### ISSUE TITLE
Use a Go-based HTTP Client or lib instead of HTTPie ?

### ISSUE THREAD

**Issue by v3ss0n** [HexmosTech/Lama2#12]
I love HTTPie , but since Python is a big dependency and since Lama2 is developed in GO , are there any plan to to use Go-Based httpclient or lib?eg:
https://github.com/nojima/httpie-go

**Comment by v3ss0n** [comment]
Also may be able to support  : 
https://github.com/ducaale/xh

https://github.com/rs/curlie

**Comment by shrsv** [comment]
That's an excellent suggestion. Right now, the windows packages are in moderation for `choco`; and still waiting approval. Will probably switch to a pure go version, once the package goes through.

**Comment by v3ss0n** [comment]
I think Curlie will be easisest to support since its written in go , and xh should be easy to bundle togehter too.

**Comment by shrsv** [comment]
Appreciate the support. I'll dig deeper into these tools and pick one.

**Comment by shrsv** [comment]
Finally settled with a mod of `httpie-go` @v3ss0n. Please take a look at latest release whenever possible.

**Comment by v3ss0n** [comment]
going to try it.

**Comment by v3ss0n** [comment]
It works , but , `httpie-go` seems unmantained and the same goes for `curlie` too.

**Comment by shrsv** [comment]
Good point. `httpie-go` is essentially CLI parsing + Standard HTTP lib + Output formatter. Moreover, the subject matter ("http requests") is a fairly stable domain. If there are any serious issues, I should be able to dive in a patch up our fork of it. As with everything, it comes with some costs/benefits :)

**Comment by v3ss0n** [comment]
i agree ,  i also saw you guys already forked and patching httpie-go so , i guess thats looks good!
