### ISSUE TITLE
get "tar: Option --overwrite is not supported" on macos install

### ISSUE THREAD

**Issue by geohuz** [HexmosTech/Lama2#9]
I'm using the command: 
```
curl -s https://hexmos.com/lama2/install.sh | bash -s
```
and getting the following error message in the end:
```
tar: Option --overwrite is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
mv: rename /tmp/l2 to /usr/local/bin/l2: No such file or directory
```

The os version: macos Ventura version 13.1

**Comment by shrsv** [comment]
Thanks for the report, will work on a fix.

Meanwhile, please head over to the [release](https://github.com/HexmosTech/Lama2/releases/tag/v1.2.2) page and place the `l2` binary in `/usr/local/bin`. Also, make sure [httpie](https://httpie.io/docs/cli) is installed in your system.

These two steps should get the tool going locally.

**Comment by shrsv** [comment]
@geohuz - Please try re-running the command now. I have removed the `--overwrite` parameter (which seems to be optional).

**Comment by geohuz** [comment]
@shrsv thanks for the update, it works now!
